; ============================================================
; Plik konfiguracyjny programu imgproc
; ============================================================

[paths]
source_dir = C:\Users\Pc\Desktop\projekt_pos\obrazy   ; folder z obrazami wejściowymi
dest_dir   = C:\Users\Pc\Desktop\projekt_pos\output  ; folder na wyniki

[processing]
num_threads    = 0    ; 0 = automatycznie (liczba rdzeni CPU)
thumbnail_size = 128  ; rozmiar boku miniatury [px]
canny_low      = 50   ; dolny próg Canny
canny_high     = 150  ; górny próg Canny
